name: Setup
description: Setup the environment

inputs:
  node-version:
    description: The version of node.js
    required: false
    default: '24'

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@739bfe42ca9233c5e6aca07c1a25a9d34aca49b0 # v6.0.7

    - name: Setup node
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: Install
      run: pnpm install
      shell: bash

    - name: Build packages
      run: pnpm run build
      shell: bash
