packages:
  - 'packages/*'
  - 'examples/*'
  - e2e

allowBuilds:
  esbuild: false
  sharp: false

strictPeerDependencies: true

linkWorkspacePackages: deep

dedupePeers: true

ignoreWorkspaceRootCheck: true

minimumReleaseAgeExclude:
  - '@ocavue/eslint-config'
  - prosemirror-view@1.42.2
