name: release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Create versions or publish to npm registry
        uses: changesets/action@198f833dd7d863100ea6e28967bc9a9fdefadb0a # v2.1.0
        with:
          publish-script: pnpm release
          commit-message: 'ci(changeset): release prosemirror-adapter'
          pr-title: 'ci(changeset): release prosemirror-adapter'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}