name: release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Create versions or publish to npm registry
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: 'ci(changeset): release prosemirror-adapter'
          title: 'ci(changeset): release prosemirror-adapter'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
